# permissions for end users to edit deploymentupgrades.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: deploymentupgrade-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: deployment-upgrade
    app.kubernetes.io/part-of: deployment-upgrade
    app.kubernetes.io/managed-by: kustomize
  name: deploymentupgrade-editor-role
rules:
- apiGroups:
  - upgrade.github.com
  resources:
  - deploymentupgrades
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - upgrade.github.com
  resources:
  - deploymentupgrades/status
  verbs:
  - get
